version '3'
services:
        webserve:
         build: .
         container_name: nginx
         restart: unless-stopped
         ports:
          - "80:80"
         
         volumes:
          - ./nginx-conf:/etc/nginx/conf.d
         
         networks:
          - app-network 
