version: '3'
services:
    sonarqube:
        build:
         context: sonarqube/
        ports:
         - 9000:900
         - 9092:9092 
        container_name: sonarqube
    
    jenkins:
        build:
         context: jenkins/
        privileged: true
        user: root
        ports:
         - 8080:8080 
         - 5000:5000
        container_name: jenkins 
        volumes:
         - /tmp/jenkins:/var/jenkins_home #Remember that, the tmp directory is designed to be wiped on system root
         - /var/run/docker.sock:/var/run/docker.sock 
        depends_on:
         - sonarqube
         
         